apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinates-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinates-api
  template:
    metadata:
      labels:
        app: coordinates-api
    spec:
      containers:
        - name: coordinates-api
          image: lmadueno/coordinates-api:latest
          ports:
            - containerPort: 3001
          env:
            - name: AMQP_URL
              value: "amqp://guest:guest@rabbitmq-service:5672"
