apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      containers:
        - name: socket-server
          image: lmadueno/socket-server:latest
          ports:
            - containerPort: 3004
          env:
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: CORS_ORIGIN
              value: "http://react-gis-app.local"
