apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: queue-sender-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: queue-sender-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
