module.exports = {
    type: "object",
    properties: {
        latitude: { type: "number" },
        longitude: { type: "number" },
        imei: { type: "string" },
        user: { type: "string" },
        user_name: { type: "string" },
        cell_number: { type: "string" },
        proceeding_type_id: { type: "integer" },
        proceeding_type: { type: "string" },
        color: { type: "string" },
        proceeding_format: { type: "string" },
        proceeding_file_url: { type: "string" },
        registration_date: { type: "string" },
    },
    required: [
        "latitude",
        "longitude",
        "imei",
        "user",
        "user_name",
        "cell_number",
        "proceeding_type_id",
        "proceeding_type",
        "color",
        "proceeding_format",
        "proceeding_file_url",
        "registration_date",
    ],
    additionalProperties: false,
};
